import { IKey } from '../typings/user'

export const modifiers: IKey[] = [
  { name: 'Alt', value: 'Alt' },
  { name: 'Control', value: 'CommandOrControl' },
  { name: 'Meta', value: 'CommandOrControl' },
  { name: 'Shift', value: 'Shift' },
]

export const numeric: IKey[] = [
  { name: '1', value: '1' },
  { name: '2', value: '2' },
  { name: '3', value: '3' },
  { name: '4', value: '4' },
  { name: '5', value: '5' },
  { name: '6', value: '6' },
  { name: '7', value: '7' },
  { name: '8', value: '8' },
  { name: '9', value: '9' },
  { name: '0', value: '0' },
]

export const alphabetic: IKey[] = [
  { name: 'a', value: 'A' },
  { name: 'b', value: 'B' },
  { name: 'c', value: 'C' },
  { name: 'd', value: 'D' },
  { name: 'e', value: 'E' },
  { name: 'f', value: 'F' },
  { name: 'g', value: 'G' },
  { name: 'h', value: 'H' },
  { name: 'i', value: 'I' },
  { name: 'j', value: 'J' },
  { name: 'k', value: 'K' },
  { name: 'l', value: 'L' },
  { name: 'm', value: 'M' },
  { name: 'n', value: 'N' },
  { name: 'o', value: 'O' },
  { name: 'p', value: 'P' },
  { name: 'q', value: 'Q' },
  { name: 'r', value: 'R' },
  { name: 's', value: 'S' },
  { name: 't', value: 'T' },
  { name: 'u', value: 'U' },
  { name: 'v', value: 'V' },
  { name: 'w', value: 'W' },
  { name: 'x', value: 'X' },
  { name: 'y', value: 'Y' },
  { name: 'z', value: 'Z' },
  { name: 'A', value: 'A' },
  { name: 'B', value: 'B' },
  { name: 'C', value: 'C' },
  { name: 'D', value: 'D' },
  { name: 'E', value: 'E' },
  { name: 'F', value: 'F' },
  { name: 'G', value: 'G' },
  { name: 'H', value: 'H' },
  { name: 'I', value: 'I' },
  { name: 'J', value: 'J' },
  { name: 'K', value: 'K' },
  { name: 'L', value: 'L' },
  { name: 'M', value: 'M' },
  { name: 'N', value: 'N' },
  { name: 'O', value: 'O' },
  { name: 'P', value: 'P' },
  { name: 'Q', value: 'Q' },
  { name: 'R', value: 'R' },
  { name: 'S', value: 'S' },
  { name: 'T', value: 'T' },
  { name: 'U', value: 'U' },
  { name: 'V', value: 'V' },
  { name: 'W', value: 'W' },
  { name: 'X', value: 'X' },
  { name: 'Y', value: 'Y' },
  { name: 'Z', value: 'Z' },
]

export const special: IKey[] = [
  { name: '+', value: 'Plus' },
  { name: ' ', value: 'Space' },
  { name: 'Tab', value: 'Tab' },
  { name: 'Escape', value: 'Esc' },
  { name: 'Capslock', value: 'Capslock' },
  { name: 'Backspace', value: 'Backspace' },
  { name: 'ArrowUp', value: 'Up' },
  { name: 'ArrownDown', value: 'Down' },
  { name: 'ArrowLeft', value: 'Left' },
  { name: 'ArrowRight', value: 'Right' },
  { name: '~', value: '~' },
  { name: '!', value: '!' },
  { name: '.', value: '.' },
  { name: ',', value: ',' },
  { name: '@', value: '@' },
  { name: '#', value: '#' },
  { name: '$', value: '$' },
]
