# workflow
# [] Create a draft release on /switch
# [] Package application and upload to draft release
# [] Generate release.json and updates.json
# [] Upload release files to draft release
# [] Publish release and make latest
# [] Clone published release to /switch-releases

# resources
# https://github.com/marketplace/actions/create-release
# https://github.com/marketplace/actions/release-assets
# https://stackoverflow.com/questions/45240336/how-to-use-github-release-api-to-make-a-release-without-source-code

name: app-publish
on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(node -pe "require('${{ github.workspace }}/app/package.json').version")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Generate Assets
        run: node app/scripts/release.js

      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          artifacts: release-assets/*.json
          draft: true

      - name: Set Release ID
        id: set_release_id
        uses: i3h/share-data@v1
        with:
          share-id: release_id
          mode: set
          key: release_id
          value: ${{ steps.create_release.outputs.id }}

  publish-release:
    needs:
      - create-release
    runs-on: ubuntu-latest
    steps:
      - name: Get Release ID
        id: get_release_id
        uses: i3h/share-data@v1
        with:
          share-id: release_id
          mode: get
          key: release_id

      - name: Publish Release
        uses: StuYarrow/publish-release@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.get_release_id.outputs.data }}

  clone-release:
    needs:
      - create-release
      - publish-release
    runs-on: ubuntu-latest
    steps:
      - name:
        run: |
          mkdir temp
          touch temp/hello-world.txt

      - name: Copy release assets
        id: Release-AIO
        uses: Hs1r1us/Release-AIO@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: inherit
          body: hello world test
          repo: olafkotur/switch-releases
