name: deploy-site

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: $GH_TOKEN
          target_branch: mainsite
